### ISSUE TITLE
Allow for Shift + Click range-select in the Grid, similar to Windows Explorer

### ISSUE THREAD

**Issue by ravhb** [microsoft/projection-grid#60]
Allow for Shift + Click multi-select in the Grid, similar to Windows Explorer

![shift](https://cloud.githubusercontent.com/assets/1821507/21393183/43c8f9da-c7ce-11e6-9c8e-bf6db4b1f954.gif)

**Comment by yaoyao-ict** [comment]
this can be done with customized grid plugin
